{"timestamp": "2023-09-01 15:34:10", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 15:34:14", "level": "ERROR", "module": "test", "function": "<module>", "line": 44, "message": "Traceback (most recent call last):\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3652, in get_loc\n    return self._engine.get_loc(casted_key)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"pandas\\_libs\\index.pyx\", line 147, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\index.pyx\", line 176, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item\nKeyError: 'DISABLE EMPL ID'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\test.py\", line 42, in <module>\n    process(config, dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\fr_process.py\", line 14, in process\n    call_data_filter.ph1_data_filter(config,dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\call_data_filter.py\", line 13, in ph1_data_filter\n    ddqc1 = Ph1FilterValidation(dict_transaction['df_ddqc_report'])\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\data_filter_ph1.py\", line 15, in __init__\n    self.general_rule()\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\general_rule.py\", line 12, in general_rule\n    self.df_gen_rule1 = self.df_input[self.df_input['DISABLE EMPL ID'].isnull() & self.df_input['CHARGE'].notna()]\n                                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\frame.py\", line 3761, in __getitem__\n    indexer = self.columns.get_loc(key)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3654, in get_loc\n    raise KeyError(key) from err\nKeyError: 'DISABLE EMPL ID'\n", "process": "ddqc"}
{"timestamp": "2023-09-01 15:35:05", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 15:35:13", "level": "ERROR", "module": "test", "function": "<module>", "line": 44, "message": "Traceback (most recent call last):\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3652, in get_loc\n    return self._engine.get_loc(casted_key)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"pandas\\_libs\\index.pyx\", line 147, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\index.pyx\", line 176, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item\nKeyError: 'DISABLE EMPL ID'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\test.py\", line 42, in <module>\n    process(config, dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\fr_process.py\", line 14, in process\n    call_data_filter.ph1_data_filter(config,dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\call_data_filter.py\", line 13, in ph1_data_filter\n    ddqc1 = Ph1FilterValidation(dict_transaction['df_ddqc_report'])\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\data_filter_ph1.py\", line 15, in __init__\n    self.general_rule()\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\general_rule.py\", line 12, in general_rule\n    self.df_gen_rule1 = self.df_input[self.df_input['DISABLE EMPL ID'].isnull() & self.df_input['CHARGE'].notna()]\n                                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\frame.py\", line 3761, in __getitem__\n    indexer = self.columns.get_loc(key)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3654, in get_loc\n    raise KeyError(key) from err\nKeyError: 'DISABLE EMPL ID'\n", "process": "ddqc"}
{"timestamp": "2023-09-01 15:43:48", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 15:43:52", "level": "ERROR", "module": "test", "function": "<module>", "line": 44, "message": "Traceback (most recent call last):\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3652, in get_loc\n    return self._engine.get_loc(casted_key)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"pandas\\_libs\\index.pyx\", line 147, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\index.pyx\", line 176, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item\nKeyError: 'DISABLE EMPL ID'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\test.py\", line 42, in <module>\n    process(config, dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\fr_process.py\", line 14, in process\n    call_data_filter.data_filter(config,dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\call_data_filter.py\", line 13, in data_filter\n    ddqc1 = Ph1FilterValidation(dict_transaction['df_ddqc_report'])\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\data_filter_ph1.py\", line 15, in __init__\n    self.general_rule()\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\general_rule.py\", line 12, in general_rule\n    self.df_gen_rule1 = self.df_input[self.df_input['DISABLE EMPL ID'].isnull() & self.df_input['CHARGE'].notna()]\n                                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\frame.py\", line 3761, in __getitem__\n    indexer = self.columns.get_loc(key)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3654, in get_loc\n    raise KeyError(key) from err\nKeyError: 'DISABLE EMPL ID'\n", "process": "ddqc"}
{"timestamp": "2023-09-01 15:44:44", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 15:44:48", "level": "ERROR", "module": "test", "function": "<module>", "line": 44, "message": "Traceback (most recent call last):\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3652, in get_loc\n    return self._engine.get_loc(casted_key)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"pandas\\_libs\\index.pyx\", line 147, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\index.pyx\", line 176, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item\nKeyError: 'DISABLE EMPL ID'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\test.py\", line 42, in <module>\n    process(config, dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\fr_process.py\", line 14, in process\n    call_data_filter.data_filter(config,dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\call_data_filter.py\", line 14, in data_filter\n    ddqc2 = Ph2FilterValidation(dict_transaction['df_ddqc_report'])\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\data_filter_ph2.py\", line 16, in __init__\n    self.general_rule()\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\general_rule.py\", line 12, in general_rule\n    self.df_gen_rule1 = self.df_input[self.df_input['DISABLE EMPL ID'].isnull() & self.df_input['CHARGE'].notna()]\n                                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\frame.py\", line 3761, in __getitem__\n    indexer = self.columns.get_loc(key)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3654, in get_loc\n    raise KeyError(key) from err\nKeyError: 'DISABLE EMPL ID'\n", "process": "ddqc"}
{"timestamp": "2023-09-01 15:47:11", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 15:52:38", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 15:52:49", "level": "ERROR", "module": "test", "function": "<module>", "line": 45, "message": "Traceback (most recent call last):\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3652, in get_loc\n    return self._engine.get_loc(casted_key)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"pandas\\_libs\\index.pyx\", line 147, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\index.pyx\", line 176, in pandas._libs.index.IndexEngine.get_loc\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item\n  File \"pandas\\_libs\\hashtable_class_helper.pxi\", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item\nKeyError: 'DISABLE EMPL ID'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\test.py\", line 43, in <module>\n    process(config, dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\fr_process.py\", line 15, in process\n    call_data_filter.ph2_data_filter(config,dict_transaction)\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\call_data_filter.py\", line 60, in ph2_data_filter\n    ddqc2 = Ph2FilterValidation(dict_transaction['df_ddqc_report'])\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\data_filter_ph2.py\", line 16, in __init__\n    self.general_rule()\n  File \"c:\\Users\\mjeevaba\\Documents\\Python\\DDQC\\DDQC 2.0\\Code\\DDQC Rule Engine\\Project\\general_rule.py\", line 12, in general_rule\n    self.df_gen_rule1 = self.df_input[self.df_input['DISABLE EMPL ID'].isnull() & self.df_input['CHARGE'].notna()]\n                                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\frame.py\", line 3761, in __getitem__\n    indexer = self.columns.get_loc(key)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mjeevaba\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\indexes\\base.py\", line 3654, in get_loc\n    raise KeyError(key) from err\nKeyError: 'DISABLE EMPL ID'\n", "process": "ddqc"}
{"timestamp": "2023-09-01 15:53:14", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 15:54:02", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 15:55:13", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 16:04:43", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 18:01:25", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 18:08:39", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 18:33:23", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 18:35:49", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 18:59:46", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
{"timestamp": "2023-09-01 20:06:27", "level": "INFO", "module": "test", "function": "<module>", "line": 34, "message": "ddqc-- execution started", "process": "ddqc"}
